name: muvy
description: ""
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Network
  dio: ^5.9.1
  cached_network_image: ^3.4.1

  # Routing
  auto_route: ^11.1.0

  # State Management
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

  # Env
  envied: ^1.3.3

  # UI
  google_fonts: ^8.0.1
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0

  # Video
  video_player: ^2.10.1
  chewie: ^1.13.0
  webview_flutter: ^4.13.1

  # Storage
  shared_preferences: ^2.5.2

  # P2P / WebRTC
  peerdart: ^0.5.6
  uuid: ^4.5.2
  share_plus: ^12.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Gen
  build_runner: ^2.11.1
  auto_route_generator:
  riverpod_generator:
  envied_generator:

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  change_app_package_name: ^1.5.0
  freezed: ^3.2.5
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/
